### ISSUE TITLE
Latest version is throwing an error

### ISSUE THREAD

**Issue by TadhgEomonn** [altairwei/Stoneshard-AutoPathfinder#3]
[00:03:35 ERR] Something went wrong
System.MissingMethodException: Attempted to access a missing method.
   at AutoPathfinder.Localization.ActionLogsPatching()
   at AutoPathfinder.AutoPathfinder.PatchMod()
   at ModShardLauncher.ModLoader.PatchMods()
   at ModShardLauncher.ModLoader.PatchFile()
   at ModShardLauncher.Controls.ModInfos.Save_Click(Object sender, EventArgs e)
[00:03:35 INF] Failed patching vanilla

**Comment by altairwei** [comment]
Fixed

**Comment by TadhgEomonn** [comment]
Verified. Thank you, sir.
